### ISSUE TITLE
You need to babel your code for support the IE

### ISSUE THREAD

**Issue by YanwuSenlu** [lindell/vue-barcode#2]

**Comment by lindell** [comment]
Does the latest changes make this work without it? I think this library is small enough to be maintained using ES5 syntax and @austinkregel was kind enough to fix the few thing that was not.

**Comment by austinkregel** [comment]
Hmmm... @YanwuSenlu is probably just referencing the need for some kind of shim library. :thinking: I'm quite curious find out which version of IE you're trying to support.

Also what's not working in IE, just saying we need babel isn't exactly helpful. :stuck_out_tongue: What babel repo are you suggesting? Have you tested this babel repo in a fork/clone? :thinking: 

My coworkers and I tested this repo using IE11, Edge, Firefox, and Chrome accross Windows, Mac and Linux. The only issue we had was compiling with `laravle-mix` as I noted in #3 

If @YanwuSenlu could provide more information I'd be happy to look into this :smile:

**Comment by YanwuSenlu** [comment]
@austinkregel ，I just copy the index.js into my project, without change any code, just use webpack && babel  in my project  , it work's well  in IE 8+.I think if your package want to support IE8+, you should babel  code before you publish  it to npm

**Comment by austinkregel** [comment]
[Microsoft only supports IE 11+ and Edge as of January of last year (2016) on all supported versions of Windows.](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support)
