### ISSUE TITLE
i can't change the style

### ISSUE THREAD

**Issue by dancoLgh** [lindell/vue-barcode#23]
hello, ignore the options I put

` <barcode :value="codigo" :option='{format: "pharmacode", width:4, height:40, displayValue: false}'> 
                    <i style="font-size:10px;" class="fa fa-spinner fa-pulse fa-fw"></i>
                   <span style="font-size:10px;">Gerando código de barras.</span>
   </barcode>   `

**Comment by vishy-experiments** [comment]
Passing individual value as prop works for me. Example:
`<barcode value="112211" :width="3" :height="25"></barcode>`
