### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by pazfelipe** [lindell/vue-barcode#30]
This is my configuration 

```javascript
<vue-barcode
     :value="codigoBarras"
     width="1"
     height="60"
     :options="{
        lineColor: '#007bff',
        fontSize: '20',
        lineColor: '#990000',
        marginLeft: 30,
        marginTop: 50,
        background: '#dddddd'
     }"
>
      Não possível renderizar a imagem
</vue-barcode>
```
![image](https://user-images.githubusercontent.com/19727571/110371423-b8f5d600-802b-11eb-9f04-f70887e1c2ae.png)

The style is not applied to the component. I'm using it on quasar framework.

And here is how it's rendered

![image](https://user-images.githubusercontent.com/19727571/110371530-ddea4900-802b-11eb-8301-3726cb6a6af7.png)

**Comment by lindell** [comment]
Options should not be wrapped in 'options'

**Comment by pazfelipe** [comment]
I've followed the instructions on the official's page. I've copied and pasted the same example that the page contains and the only thing you say me is `Options should not be wrapped in 'options'`.  That's quite unrespectful.
